Updating your SDK via git
gamemanual0/gm0 pull request #170
Opened 2021-04-12 15:56 UTC by shaunsingh

Fixes https://github.com/gamemanual0/gm0/issues/113, 

Todo: fix linting, fix images

2021-04-12 19:27 UTC, dansman805 requested changes

2021-04-12 19:27 UTC, dansman805 commented on source/docs/software/using-android-studio.rst
> +The SDK can be updated through the use of git and version control. In order to update the SDK, we will first need to set the source of the updates through git upstream, and then merge the updates int
```suggestion
The SDK can be updated through the using the version control software Git. In order to update the SDK, we will first need to set the source of the updates using Git remotes, and then merge the updates into our current project.
```

2021-04-12 19:27 UTC, dansman805 commented on source/docs/software/using-android-studio.rst
> +.. note:: Your FTC project needs to be set up as a Github Repository prior to following this guide.
```suggestion
.. note:: Your FTC project needs to be set up as a Git repository prior to following this guide.
```

2021-04-12 19:27 UTC, dansman805 commented on source/docs/software/using-android-studio.rst
> +^^^^^^^^^^^^^^^^^^^^
```suggestion
Setting Git Remote
^^^^^^^^^^^^^^^^^^
```

2021-04-12 19:27 UTC, dansman805 commented on source/docs/software/using-android-studio.rst
> +#. Open up your project in android studio
```suggestion
#. Open up your project in Android Studio
```

2021-04-12 19:27 UTC, dansman805 commented on source/docs/software/using-android-studio.rst
> +Merge conflicts occur when competing changes are made to the same line of a file. If you modified gradle files within your project, it is very likely you will run into a merge conflict when updating
```suggestion
Merge conflicts occur when competing changes are made to the same line of a file. If you modified Gradle files within your project, it is very likely you will run into a merge conflict when updating the SDK.
```

2021-04-12 21:08 UTC, dansman805 approved these changes

2021-04-12 21:09 UTC, NoahAndrews commented
The other thing that this should probably explain is how to start the git project from the official repository. If you just start a brand new history, these instructions won't work as expected.

2021-04-12 22:06 UTC, shaunsingh commented
The recommended way would be to fork the project and set the remote to ,correct

2021-04-12 22:08 UTC, dansman805 commented on source/docs/software/using-android-studio.rst
> +.. note:: The command above assumes you're using the FTC SDK. If you are using a modified version of the SDK as your base (e.g. Roadrunner Quickstart), replace the git link with one from the modified
```suggestion
.. note:: The command above assumes you're using the FTC SDK. If you are using a modified version of the SDK as your base (e.g. Road Runner Quickstart), replace the git link with one from the modified SDK repo
```

2021-04-12 22:10 UTC, dansman805 commented
> The recommended way would be to fork the project and set the remote to ,correct

The recommended way is to clone the project, and then if using GitHub, making a new repository there and pushing there. GitHub forks are meant for submitting pull requests.

2021-04-16 03:08 UTC, shaunsingh commented
If possible, could someone kindly write how to upload to GitHub using the Cli? I don't have any experience myself.

2021-04-16 18:38 UTC, shaunsingh commented
fixes https://github.com/gamemanual0/gm0/issues/111

2022-08-13 04:21 UTC, Eeshwar-Krishnan commented
I think all that needs to be done is merge this with the current gm0 to clear merge conflicts?

2022-08-13 23:02 UTC, Eeshwar-Krishnan commented
closing as out of scope after some discussion, teaching the basics of how to use git and deal with merge conflicts quickly becomes way out of scope for basic use

2022-08-13 23:02 UTC, closed without merging

2022-08-13 23:04 UTC, abidingabi commented
For slightly more context, if you want to explain updating the SDK, you have to cover:
- cloning
- staging
- commiting
- remotes
- pulling
- merge conflicts
- probably also at this point pushing in order to collaborate/backup your code

Yes gm0 *could* cover this but if it'll end up being a decently fully-featured git tutorial plenty of those already exist