Encoders 101
gamemanual0/gm0 pull request #300
Opened 2022-11-08 02:45 UTC by Eeshwar-Krishnan

Thank you to 7236 Ethan for the idea

2023-01-14 00:03 UTC, abidingabi requested changes
A bunch of little suggestions. The page also needs blocks examples code.

2023-01-14 00:03 UTC, abidingabi commented on source/docs/software/tutorials/encoders.rst
> +                        double position = motor.getCurrentPosition();
```suggestion
                        int position = motor.getCurrentPosition();
```

2023-01-14 00:03 UTC, abidingabi commented on source/docs/software/tutorials/encoders.rst
> +                        double angle_normalized = angle % 360;
```suggestion
                        double angleNormalized = angle % 360;
```

2023-01-14 00:03 UTC, abidingabi commented on source/docs/software/tutorials/encoders.rst
> +                        telemetry.addData("Encoder Angle - Normalized (Degrees)", angle_normalized);
```suggestion
                        telemetry.addData("Encoder Angle - Normalized (Degrees)", angleNormalized);
```

2023-05-18 02:32 UTC, colloquist approved these changes

2023-05-18 02:34 UTC, abidingabi approved these changes

2023-05-18 20:32 UTC, merged