add hivemind cad + port to gallery
gamemanual0/gm0 pull request #437
Opened 2024-07-30 18:22 UTC by polargh

2024-07-31 00:13 UTC, abidingabi requested changes

2024-07-31 00:13 UTC, abidingabi commented on source/docs/appendix/gallery.rst
> +- `Portfolio <https://go.hivemindrobotics.net/csportfolio>`__
Please do not use link shorteners, or your own hosting for your portfolio—we would rather link to somewhere that we know will last.

2024-07-31 00:13 UTC, abidingabi commented on source/docs/appendix/gallery.rst
> +23396 hivemind
The teams within a given season are sorted in numerical order, and so hivemind should be last out of the teams present for Center Stage.

2024-07-31 00:52 UTC, abidingabi commented on source/docs/appendix/gallery.rst
> +- `Portfolio <https://www.dropbox.com/scl/fi/djsasr2ofjwxe2u6x30q4/23396-CS.pdf?rlkey=i6i2m0biob18iiegup48wnkus&st=kntv960r&dl=0>`__
```suggestion
- `CAD <https://cad.onshape.com/documents/fba422c04d9f259e36433b8c/w/661ed7aa8a40b6c0f5d26203/e/6205d0d7691937476f4d9a4c>`__
- `Portfolio <https://www.dropbox.com/scl/fi/djsasr2ofjwxe2u6x30q4/23396-CS.pdf>`__
```

2024-07-31 00:53 UTC, abidingabi commented on source/docs/appendix/gallery.rst
> +- `Portfolio <https://www.dropbox.com/scl/fi/djsasr2ofjwxe2u6x30q4/23396-CS.pdf?rlkey=i6i2m0biob18iiegup48wnkus&st=kntv960r&dl=0>`__
```suggestion
- `CAD <https://cad.onshape.com/documents/fba422c04d9f259e36433b8c/w/661ed7aa8a40b6c0f5d26203/e/6205d0d7691937476f4d9a4c>`__
- `Portfolio <https://www.dropbox.com/scl/fi/djsasr2ofjwxe2u6x30q4/23396-CS.pdf>`__
```

2024-07-31 00:59 UTC, abidingabi approved these changes

2024-07-31 00:59 UTC, merged

2024-08-01 00:24 UTC, ArushYadlapati commented
wow its hivemmind